### ISSUE TITLE
Gallery release

### ISSUE THREAD

**Issue by rocksdanister** [rocksdanister/lively#1287]
Progress tracking for gallery development.

- [ ] [Microsoft store policy compliance](https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies)
  - [ ] [Digital Storefront content.](https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies#1113-third-party-digital-storefronts-content)
    - [ ] Publish and make available a developer and/or publisher terms of service and content guidelines for products listed in your marketplace.
    - [ ] Provide a means for users to report inappropriate content, or content that violates your terms of service or content guidelines.
    - [ ] Implement a method for review and detection of content that is in violation of your terms or guidelines and take enforcement actions.
    - [ ] Comply with all legal and regulatory requirements regarding operations of digital storefronts.
  - [ ] [User generated content.](https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies#1112-user-generated-content)
  - [ ] [Content filter and Age rating.](https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies#1111-age-ratings)
  - [ ] [Offensive content.](https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies#115-offensive-content)
- [ ] Implement account
  - [x] Google login (OAuth)
  - [x] Github login (OAuth)
  - [ ] Discord login (OAuth)
  - [ ] Microsoft (OAuth) for Chinese users? https://github.com/rocksdanister/lively/issues/1276#issuecomment-1171699588
- [x] Account Login page.
- [ ] Account manage page.
  - [ ] Export account data.
  - [x] Delete account.
- [x] All wallpaper gallery page.
- [ ] Featured wallpaper gallery page.
- [x] Gallery library page to manage subscription.
- [ ] Wallpaper management
  - [x] Download & Subscribe wallpaper.
  - [x] Delete & Unsubscribe wallpaper.
  - [x] Restore subscribed wallpaper(s) if missing in library.
  - [ ] Wallpaper versioning and updates.
  - [x] Prompt user when client program is closed while download is ongoing.
  - [x] Wallpaper rating (thumbs up/down.)
  - [ ] Wallpaper favourite.
  - [x] Wallpaper tags.
- [x] Disk cache thumbnails.
- [ ] Back up and restore application settings.
- [ ] Abstract gallery library for future use.
- [ ] Internal beta testing.

**Comment by rocksdanister** [comment]
Login

https://user-images.githubusercontent.com/17554161/177141199-e15b1d31-3750-4374-8336-78bb809280da.mp4

Wallpaper download UI/UX

https://user-images.githubusercontent.com/17554161/177141732-751947fe-7107-46ef-97e0-363d7ab8b481.mp4

Restore wallpaper

![unknown (1)](https://user-images.githubusercontent.com/17554161/180666689-3fb4ce4d-d4fa-42ee-a812-58318945495a.png)

Report wallpaper

![Screenshot 2022-07-23 163555](https://user-images.githubusercontent.com/17554161/180666717-75360d25-7901-4428-bcbc-ba71a269d68b.jpg)

Manage wallpaper

![Screenshot 2022-07-25 031735](https://user-images.githubusercontent.com/17554161/180667225-ecb7b1c3-b5de-4d09-9536-3f4ea1611b24.jpg)

**Comment by roxxel** [comment]
So that means I have to rewrite my code to use auth0? crap

**Comment by roxxel** [comment]
Google & Github is done

**Comment by roxxel** [comment]
Discord login in work

**Comment by ecr-oha-lime** [comment]
可以添加点赞功能，用于评级精选
=======translate=======
I think it's possible to add a like feature for rating picks.

**Comment by roxxel** [comment]
It's already implemented, you can upvote and downvote wallpaper

**Comment by roxxel** [comment]
Wallpaper tags & rating is already implemented on backend

**Comment by ecr-oha-lime** [comment]
分享功能？
What aboat share function?

**Comment by ecr-oha-lime** [comment]
最后一幅图，在...中添加编辑壁纸的选项好么？其实就是添加Devtools。
======translate=======
The last picture, add the option to edit the wallpaper in ... please? In fact, it is to add Devtools.

**Comment by rocksdanister** [comment]
Share is not planned for first release.

**Comment by kitiki1222** [comment]
when is the gallery releasing

**Comment by IAMGamerJohri** [comment]
Where to download gallery release

**Comment by PentaTech** [comment]
what happened to this feature?

**Comment by BennettFourr** [comment]
Any updates?

**Comment by roxxel** [comment]
> Any updates?

dani works on fixing bugs within lively and weather app, this feature is postponed, although no one knows when it will come out

**Comment by FujiwaraChoki** [comment]
Why not just remove it entirely if it's not going to come out? I mean I don't see the point in marking it as "Coming Soon."...

**Comment by rocksdanister** [comment]
Its coming, just different implementation from original demos.

Screensaver enhancement (done) and wallpaper playlist feature has to release before it.

**Comment by FujiwaraChoki** [comment]
> Its coming, just different implementation from original demos.
> 
> Screensaver enhancement (done) and wallpaper playlist feature has to release before it.

Ah I see. Well don't feel pressured either case. Sick stuff. Thank you!

**Comment by matthieuEv** [comment]
Hey, any news about this?

**Comment by rocksdanister** [comment]
Started designing wallpaper playlist, gallery (or a version of it anyway) will be after that update.
